### ISSUE TITLE
Different wireless network

### ISSUE THREAD

**Issue by tnmendes** [ivanbeldad/kasa-go#2]
This is working if you are in a diferent wireless network from the TP-link devices? 

I am getting status equal to 0 when i am using other networks

**Comment by Jake-Mok-Nelson** [comment]
When you say status do you mean the property RelayStatus = 0 ? I think that means the device is turned off.
I think this works through the internet via the API key to Kasa (TP-Link).

**Comment by ivanbeldad** [comment]
Like @Jake-Mok-Nelson said, status 0 means the device it's turned off.
And yes, it works across different networks.
Closing this issue.

**Comment by tnmendes** [comment]
Thank you, guys!!! Worked with other wireless networks the problem is that I tested using phone as a personal hotspot and din't work and keep not working, probably some issue related with my phone internet provider.
